name: orlogo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

dependencies:
  firebase_core: ^3.9.0      # Шинэ хувилбар
  firebase_auth: ^5.3.4      # Шинэ хувилбар
  firebase_auth_web: ^5.13.5  # Шинэ хувилбар
  cloud_firestore: ^5.6.0   # Хамгийн сүүлийн тогтвортой хувилбар
  firebase_storage: ^12.3.7
  




